# ===================================================================
# GENERAL PROPERTIES
# ===================================================================
server:
  port: 8080
  tomcat:
    max-http-form-post-size: 20MB
    max-swallow-size: 20MB
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/archetype
    username: ENC(77NlOX9VvQOchzx6SOS9eTs5w7zNj2hxoKe3BLugPg+XLBYbZrJfNBDDhO4ycpA1)
    password: ENC(pb6+XoSEso7rWadRCxfg2GusDMBPGCRlsQ9q6VAZr6X5fOmpJaOp+9YF0W7aSJE5)
  jpa:
    naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    hibernate.ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
  # HikariCP specific configuration
  hikari:
    pool-name: MySqlHikariCP
    auto-commit: true
    connection-timeout: 30000  # 30 seconds
    idle-timeout: 600000       # 10 minutes
    max-lifetime: 1800000      # 30 minutes
    maximum-pool-size: 10
    minimum-idle: 10
    leak-detection-threshold: 60000 # 1 minute
    # MySQL-specific optimizations for prepared statement caching
    data-source-properties:
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      useServerPrepStmts: true
      rewriteBatchedStatements: true # Recommended for batch inserts/updates
# ===================================================================
# LOG PROPERTIES
# ===================================================================
logging:
  level:
    com.moontech: DEBUG
    org:
      springframework.data: DEBUG
      hibernate:
        SQL: DEBUG
        type.descriptor.sql.BasicBinder: TRACE

# ===================================================================
# SECURITY PROPERTIES
# ===================================================================
security:
  jwt:
    key: ENC(3BPPvq63hexKPAjBtJqkmd8OTce3zZ9JNpKWFCt6JTu3TqFB0y+Ck8R2GStuoFgnd2FlLqU3AbsEog16uJfOW5BYeyBAgYCXhMJn51KjpzyuCA3SKU0Y9MNDwQLWQmJM6QWyhwut5OWj8OqTAYlKKlvw5qpJTT1HoMgCpVdtmvwY1JIYOg/Imazvw9+R/Yw3TE+MCQLouUw5v3whZ58Q7g==)
    lifeTime: 631138000000
  cors:
    origins:
      http://127.0.0.1:4200,
      http://localhost:4200,
      http://localhost:4201
