# ===================================================================
# GENERAL PROPERTIES
# ===================================================================
server:
  port: 8080
  tomcat:
    max-http-form-post-size: 20MB
    max-swallow-size: 20MB
spring:
  application:
    name: archetype-service
  main.banner-mode: off
  flyway:
    enabled: true
    locations: classpath:/db/migration
    baseline-on-migrate: true
    baseline: 0
# ===================================================================
# LOG PROPERTIES
# ===================================================================
logging:
  pattern:
    file: '[%X{data}%thread] [%X{X-B3-TraceId:-}] - %5p'
    console: "%p [${spring.application.name:}, %d{'yyyy-MM-dd HH:mm:ss,SSS',America/Mexico_City}, %C{1}:%M:%L, %X{mdc.uuid}, %m%n%ex{3}"

# ===================================================================
# PATH PROPERTIES
# ===================================================================
api:
  uri:
    domain:
      users: /users
    data:
      authentication: ${api.uri.domain.users}/authentication